### ISSUE TITLE
Reaction Roles

### ISSUE THREAD

**Issue by Tqggle** [zapteryx/Zap#4]
**Is your feature request related to a problem? Please describe.**
Nope. Simply add region reaction roles such as North America, South America (with flags).
**Describe the solution you'd like**
Mentioned above.
**Describe alternatives you've considered**
Mentioned above.
**Additional context**
Nope.

**Comment by zapteryx** [comment]
As Zap is a community bot, the feature will be altered to fit the purpose of the bot.
Changes:
+ Add reaction roles for server admins, and make it configurable for easy addition and removal of reaction roles.

**Comment by zapteryx** [comment]
Will need more time on this as I'm unsure of how I'm going to be implementing it.

**Comment by zapteryx** [comment]
Going to customize the module for the server instead, refer to https://github.com/zptxp/Zap-MSU for future updates.
